### ISSUE TITLE
CUFFT_INTERNAL_ERROR when attempting torch.stft

### ISSUE THREAD

**Issue by AznamirWoW** [lshqqytiger/ZLUDA#29]
Tried zluda 3.72 and 3.80-rocm5 with torch 2.1.1 cu118 and 2.3.0 cu118

Traceback (most recent call last):
  File "G:\fft_test\fft.py", line 5, in <module>
    fft = torch.stft(
  File "G:\fft_test\venv\lib\site-packages\torch\functional.py", line 665, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

attached the test script and with tensor files
[fft_test.zip](https://github.com/user-attachments/files/16203801/fft_test.zip)

**Comment by AznamirWoW** [comment]
just a simple test code with a dummy tensor fails as well

import torch
dev = torch.device("cuda")
t_audio = torch.randn(1, 2048, device=dev)
fft_tensor = torch.fft.fft(t_audio)

**Comment by lshqqytiger** [comment]
Unfortunately, AMD HIP SDK does not have an equivalent of cuFFTW, which is a requirement of PyTorch FFT.
Therefore, at this moment, it is not able to run torch.sfft using ZLUDA.
